/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_cn_smilex_libhv_jni_Requests
#define _Included_cn_smilex_libhv_jni_Requests
#ifdef __cplusplus
extern "C" {
#endif

/*
 * 以Get方式请求指定网站并返回结果
 * Class:     cn_smilex_libhv_jni_http_Requests
 * Method:    get
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 * Author:	  Smilex
 */
JNIEXPORT jstring JNICALL Java_cn_smilex_libhv_jni_http_Requests_get
  (JNIEnv* env, jobject, jstring url);

/*
 * 以Post方式请求指定网站并返回结果
 * Class:     cn_smilex_libhv_jni_http_Requests
 * Method:    post
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 * Author:	  Smilex
 */
JNIEXPORT jstring JNICALL Java_cn_smilex_libhv_jni_http_Requests_post
  (JNIEnv* env, jobject, jstring url);

/*
 * 通过HttpRequest类请求指定网站并返回HttpResponse
 * Class:     cn_smilex_libhv_jni_http_Requests
 * Method:    request
 * Signature: (Lcn/smilex/libhv/jni/http/HttpRequest;)Ljava/lang/String;
 */
JNIEXPORT jobject JNICALL Java_cn_smilex_libhv_jni_http_Requests_request
  (JNIEnv* env, jobject, jobject request);

/*
 * Class:     cn_smilex_libhv_jni_ssl_MD5
 * Method:    getMD5
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_smilex_libhv_jni_ssl_MD5_getMD5
        (JNIEnv* env, jobject, jstring data, jint len);

#ifdef __cplusplus
}
#endif
#endif
